"""rename file_path to file_key

Revision ID: 86493de11fa1
Revises: c53ae740041e
Create Date: 2026-04-03 19:41:47.223962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86493de11fa1'
down_revision: Union[str, Sequence[str], None] = 'c53ae740041e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE medical_files RENAME COLUMN file_path TO file_key")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_patient_visit'), 'visits', ['patient_id', 'visit_id'], postgresql_nulls_not_distinct=False)
    op.execute("ALTER TABLE medical_files RENAME COLUMN file_key TO file_path")
    op.create_unique_constraint(op.f('admissions_admission_id_key'), 'admissions', ['admission_id'], postgresql_nulls_not_distinct=False)
    op.create_table('pays',
    sa.Column('payment_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('mpesa_receipt', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('checkout_request_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reference', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('payment_id', name=op.f('pays_pkey')),
    sa.UniqueConstraint('checkout_request_id', name=op.f('pays_checkout_request_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('mpesa_receipt', name=op.f('pays_mpesa_receipt_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_pays_payment_id'), 'pays', ['payment_id'], unique=False)
    op.create_table('bill_items',
    sa.Column('item_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('bill_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.bill_id'], name=op.f('bill_items_bill_id_fkey')),
    sa.PrimaryKeyConstraint('item_id', name=op.f('bill_items_pkey'))
    )
    op.create_index(op.f('ix_bill_items_item_id'), 'bill_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_bill_items_bill_id'), 'bill_items', ['bill_id'], unique=False)
    # ### end Alembic commands ###
